In [1]:
import numpy as np
import  pandas as pd
from sklearn.metrics import f1_score
import matplotlib.pyplot as plt
from sklearn import linear_model
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn import model_selection
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
from sklearn.naive_bayes import GaussianNB
from sklearn.ensemble import BaggingClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import VotingClassifier


cd=pd.read_csv("telecom.csv")
cdf=pd.DataFrame(cd)
list1 = [ 'OnlineSecurity', 'OnlineBackup', 'DeviceProtection',
                'TechSupport','StreamingTV', 'StreamingMovies']
for i in list1:
    cdf[i] = cdf[i].replace({'No internet service':'No'})
cdf['MultipleLines'] = cdf['MultipleLines'].replace({'No phone service':'No'})

list2=[ 'OnlineSecurity', 'OnlineBackup', 'DeviceProtection','Churn',
                'TechSupport','StreamingTV', 'StreamingMovies','MultipleLines','Partner','Dependents','PaperlessBilling','PhoneService']
for i in list2:
    cdf[i]= cdf[i].replace({'Yes':1,'No':0})
gen=pd.get_dummies(cdf["gender"],drop_first = True)
cdf=pd.concat((cdf,gen),axis=1)
cdf.drop(['gender'],axis=1,inplace=True)
y=pd.get_dummies(cdf["InternetService"])
y.drop(['No'],axis=1,inplace=True)
cdf.drop(['InternetService'],axis=1,inplace=True)
cdf=pd.concat((cdf,y),axis=1)
x=pd.get_dummies(cdf["Contract"])
cdf.drop(["Contract"],axis=1,inplace=True)
cdf=pd.concat((cdf,x),axis=1)
cdf.drop(["PaymentMethod"],axis=1,inplace=True)
cdf.drop(["customerID"],axis=1,inplace=True)
cdf['tenure']=cdf['tenure'].replace({0:0.1})
ten=np.log(cdf['tenure'])
cdf.drop(["tenure"],axis=1,inplace=True)
cdf=pd.concat((cdf,ten),axis=1)
cdf['TotalCharges'] =pd.to_numeric(cdf['TotalCharges'], errors ='coerce')
z=cdf.dropna()
index =cdf['TotalCharges'].index[cdf['TotalCharges'].apply(np.isnan)]
c=[]
c.extend(index)

d=cdf.loc[c,["MonthlyCharges"]]


x= z["MonthlyCharges"].values

m=len(x)
x=x.reshape((m,-1))




y= z["TotalCharges"].values
y = y.reshape((m,-1))

regmodel=linear_model.LinearRegression()
x_train,x_test,y_train,y_test= train_test_split(x,y,test_size=0.3,random_state=42)
regmodel.fit(x_train,y_train)
a= regmodel.predict(d)

list1=[]
for i in a:
    list1.extend(i)

r2= regmodel.score(x,y)
print("Accuracy of linear model used for predicting a null values of TotalCharges in the data set : ", r2)

for i in list1:
    cdf['TotalCharges']=(cdf['TotalCharges'].fillna(i,limit= 1))


tc=np.log(cdf['TotalCharges'])
cdf.drop(['TotalCharges'],axis=1,inplace=True)
cdf=pd.concat((cdf,tc),axis=1)
mc=np.log(cdf['MonthlyCharges'])
cdf.drop(['MonthlyCharges'],axis=1,inplace=True)
cdf=pd.concat((cdf,mc),axis=1)

cdf=cdf.abs()

from sklearn.model_selection import train_test_split
x=cdf.drop('Churn',axis=1)
y=cdf['Churn']


x_train,x_test,y_train,y_test= train_test_split(x,y,test_size=0.3,random_state=1)


kfold = model_selection.KFold(n_splits=10, random_state =42)

Accuracy of linear model used for predicting a null values of TotalCharges in the data set :  0.4238558780398537


In [55]:
# logistic regression


logmodel= LogisticRegression()
logmodel.fit(x_train,y_train)
pre=logmodel.predict(x_test)

print()

print("Accuracy of the logistic model:  " , accuracy_score(y_test, pre)*100)
print("F1_score of the model: ", f1_score(y_test,pre)*100)
print()
res=confusion_matrix(y_test,pre)
print("Confusion matrix :")
print(res)
print()
results=model_selection.cross_val_score(classifier,x,y,cv=kfold)*100
print("cross validation of the model:  ",results)
print()
print("Mean of the result of the cross validation: ",results.mean())

C:\Users\Slok\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)



Accuracy of the logistic model:   81.21154756270705
F1_score of the model:  59.69543147208122

Confusion matrix :
[[1422  163]
 [ 234  294]]

cross validation of the model:   [81.41843972 80.85106383 79.43262411 82.52840909 79.6875     77.69886364
 80.53977273 78.97727273 79.11931818 81.25      ]

Mean of the result of the cross validation:  80.15032640232108


In [35]:

#decision tree

classifier_entropy = DecisionTreeClassifier(criterion='entropy', random_state=42, max_depth = 20 )
classifier_entropy.fit(x_train,y_train)
y_ped=classifier_entropy.predict(x_test)

print("Accuracy of Decision tree model : ",accuracy_score(y_test,y_ped)*100)
print()
print("Confusion Matrix:")
print(confusion_matrix(y_test,y_ped))
print()
print("F1_score of Decision tree model : ", f1_score(y_test,y_ped)*100)
print()
classifier=DecisionTreeClassifier(criterion='entropy', random_state=42, max_depth = 3 )
results=model_selection.cross_val_score(classifier,x,y,cv=kfold)*100
print("cross validation of Decision tree model :  ",results)
print()
print("Mean of the result of the cross validation: ",results.mean() )

Accuracy of Decision tree model :  74.15996213913867

Confusion Matrix:
[[1296  289]
 [ 257  271]]

F1_score of Decision tree model :  49.81617647058824

cross validation of Decision tree model :   [80.28368794 78.86524823 77.73049645 80.68181818 79.11931818 76.42045455
 80.39772727 76.98863636 79.40340909 79.54545455]

Mean of the result of the cross validation:  78.94362508059316


In [36]:
#KNN

classifier=KNeighborsClassifier(n_neighbors=83,metric='euclidean')
classifier.fit(x_train,y_train)
y_pred =classifier.predict(x_test)

print("Accuracy of KNN model : ",accuracy_score(y_test,y_pred)*100)
print()
print("Confusion Matrix:")
print(confusion_matrix(y_test,y_pred))
print()
print("F1_score of KNN model : ", f1_score(y_test,y_pred)*100)
print()
classifier=KNeighborsClassifier(n_neighbors=83,metric='euclidean')
results=model_selection.cross_val_score(classifier,x,y,cv=kfold)*100 
print("cross validation of KNN model:  ",results)
print()
print("Mean of the result of the cross validation: ",results.mean())

Accuracy of KNN model :  80.88026502602933

Confusion Matrix:
[[1404  181]
 [ 223  305]]

F1_score of KNN model :  60.15779092702169

cross validation of KNN model:   [81.41843972 80.85106383 79.43262411 82.52840909 79.6875     77.69886364
 80.53977273 78.97727273 79.11931818 81.25      ]

Mean of the result of the cross validation:  80.15032640232108


In [37]:
# Naive bayes

label=list(y_train)
l=x_train
model=GaussianNB()
model.fit(l,label)
predicted=model.predict(x_test) 
print(" Accuracy of Naive bayes model : ",accuracy_score(y_test,predicted)*100)
print()
print("Confusion matrix:")
print(confusion_matrix(y_test,predicted))
print()
print("F1 score of Naive bayes model  :  ",f1_score(y_test,predicted)*100)
print()
results=model_selection.cross_val_score(model,x,y,cv=kfold)*100
print("cross validation of navie bayes model:  ",results)
print()
print("Mean of the result of the cross validation: ",results.mean())


 Accuracy of Naive bayes model :  74.06530998580217

Confusion matrix:
[[1124  461]
 [  87  441]]

F1 score of Naive bayes model  :   61.678321678321666

cross validation of navie bayes model:   [73.19148936 73.33333333 75.17730496 74.43181818 72.15909091 70.45454545
 71.875      73.15340909 71.875      73.15340909]

Mean of the result of the cross validation:  72.88044003868472


In [38]:
#bagging classifier using Decision Tree!
cart= DecisionTreeClassifier()
num_tree =100
model = BaggingClassifier(base_estimator=cart, n_estimators= num_tree, random_state=7)

model.fit(x_train,y_train)
y_ped=model.predict(x_test)

print("Accuracy of the model : ",accuracy_score(y_test,y_ped)*100)
print()
print("confusion Matrix:")
print(confusion_matrix(y_test,y_ped))
print()
print("F1_score of the model : ", f1_score(y_test,y_ped)*100)
print()
results=model_selection.cross_val_score(model,x,y,cv=kfold)*100
print()
print("Ensemble learner model of type bagging: ")
print()
print("list of accuracy: ",results)
print()
print("Accuracy: of bagging classifier using Decision tree model: ", results.mean())
print()

Accuracy of the model :  79.08187411263606

confusion Matrix:
[[1389  196]
 [ 246  282]]

F1_score of the model :  56.063618290258454


Ensemble learner model of type bagging: 

list of accuracy:  [79.85815603 77.73049645 77.30496454 77.84090909 79.11931818 74.57386364
 78.125      78.26704545 80.39772727 77.98295455]

Accuracy: of bagging classifier using Decision tree model:  78.12004352030947



In [39]:
#Random forest
num_tree =100
max_features =5
kfold= model_selection.KFold(n_splits=10, random_state=7)
model = RandomForestClassifier( n_estimators= num_tree,max_features=max_features,random_state=7)

model.fit(x_train,y_train)
y_ped=model.predict(x_test)

print("Accuracy of the model : ",accuracy_score(y_test,y_ped)*100)
print()
print("confusion Matrix: ")
print(confusion_matrix(y_test,y_ped))
print()
print("F1_score of the model : ", f1_score(y_test,y_ped)*100)
print()
results=model_selection.cross_val_score(model,x,y,cv=kfold)*100
print("Ensemble model of type Randomforest : ")
print()
print("list of accuracy: ",results)
print()
print("Accuracy: of random forest using Decision tree model: ", results.mean())


Accuracy of the model :  80.17037387600567

confusion Matrix: 
[[1417  168]
 [ 251  277]]

F1_score of the model :  56.93730729701954

Ensemble model of type Randomforest : 

list of accuracy:  [80.70921986 80.56737589 77.73049645 78.125      79.82954545 75.28409091
 80.82386364 77.69886364 80.25568182 79.11931818]

Accuracy: of random forest using Decision tree model:  79.01434558349452


In [40]:
#voting using logistic reg. and Decision Tree!

estimators= []
model1= LogisticRegression()
estimators.append(('logistic',model1))
model2= DecisionTreeClassifier()

estimators.append(('cart',model2))
ensemble=VotingClassifier(estimators)
ensemble.fit(x_train,y_train)
y_ped=ensemble.predict(x_test)
print("Accuracy of the model : ",accuracy_score(y_test,y_ped)*100)
print()
print("confusion Matrix: ")
print(confusion_matrix(y_test,y_ped))
print()
print("F1_score of the model : ", f1_score(y_test,y_ped)*100)
print()
results=model_selection.cross_val_score(model,x,y,cv=kfold)*100
print("voting model:  ")
print()
print("list of accuracy: ",results)
print()
print("Accuracy: of the voting classifier using logistic regression and Decision tree: ", results.mean())


C:\Users\Slok\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


Accuracy of the model :  80.26502602934217

confusion Matrix: 
[[1489   96]
 [ 321  207]]

F1_score of the model :  49.81949458483755

voting model:  

list of accuracy:  [80.70921986 80.56737589 77.73049645 78.125      79.82954545 75.28409091
 80.82386364 77.69886364 80.25568182 79.11931818]

Accuracy: of the voting classifier using logistic regression and Decision tree:  79.01434558349452


In [41]:
#bagging classifier using naive bayes!
cart=GaussianNB()
num_tree =100
model = BaggingClassifier(base_estimator=cart, n_estimators= num_tree, random_state=7)

model.fit(x_train,y_train)
y_ped=model.predict(x_test)

print("Accuracy of the model : ",accuracy_score(y_test,y_ped)*100)
print()
print("confusion Matrix: ")
print(confusion_matrix(y_test,y_ped))
print()
print("F1_score of the model : ", f1_score(y_test,y_ped)*100)
print()
results=model_selection.cross_val_score(model,x,y,cv=kfold)*100
print()
print("Ensemble learner model of type bagging: ")
print()
print("list of accuracy: ",results)
print()
print("Accuracy: of bagging classifier using Decision tree model: ", results.mean())
print()

Accuracy of the model :  74.3019403691434

confusion Matrix: 
[[1129  456]
 [  87  441]]

F1_score of the model :  61.89473684210526


Ensemble learner model of type bagging: 

list of accuracy:  [73.19148936 73.4751773  75.31914894 74.43181818 72.30113636 70.59659091
 71.875      73.4375     72.15909091 73.29545455]

Accuracy: of bagging classifier using Decision tree model:  73.00824065119276



In [42]:
#voting with logistic and Naive bayes!
estimators= []
model1= LogisticRegression()
estimators.append(('logistic',model1))
model2= GaussianNB()
estimators.append(('cart',model2))
ensemble=VotingClassifier(estimators)
ensemble.fit(x_train,y_train)
y_ped=ensemble.predict(x_test)
print("Accuracy of the model : ",accuracy_score(y_test,y_ped)*100)
print()
print("confusion Matrix: ")
print(confusion_matrix(y_test,y_ped))
print()
print("F1_score of the model : ", f1_score(y_test,y_ped)*100)
print()
results=model_selection.cross_val_score(model,x,y,cv=kfold)*100
print("voting model:  ")
print()
print("list of accuracy: ",results)
print()
print("Accuracy: of the voting classifier using logistic regression and naive bayes: ", results.mean())


C:\Users\Slok\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


Accuracy of the model :  81.21154756270705

confusion Matrix: 
[[1423  162]
 [ 235  293]]

F1_score of the model :  59.61342828077314

voting model:  

list of accuracy:  [73.19148936 73.4751773  75.31914894 74.43181818 72.30113636 70.59659091
 71.875      73.4375     72.15909091 73.29545455]

Accuracy: of the voting classifier using logistic regression and naive bayes:  73.00824065119276


In [50]:
#voting with logistic, Naive bayes and KNN!
estimators= []
model1= LogisticRegression()
estimators.append(('logistic',model1))
model2= GaussianNB()
estimators.append(('cart',model2))
model3= KNeighborsClassifier(n_neighbors=83,metric='euclidean')
estimators.append(('KNN',model3))
ensemble=VotingClassifier(estimators)
ensemble.fit(x_train,y_train)
y_ped=ensemble.predict(x_test)
print("Accuracy of the model : ",accuracy_score(y_test,y_ped)*100)
print()
print("confusion Matrix: ")
print(confusion_matrix(y_test,y_ped))
print()
print("F1_score of the model : ", f1_score(y_test,y_ped)*100)
print()
results=model_selection.cross_val_score(model,x,y,cv=kfold)*100
print("voting model:  ")
print()
print("list of accuracy: ",results)
print()
print("Accuracy: of the voting classifier using logistic regression,naive bayes and K-NN: ", results.mean())

C:\Users\Slok\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


Accuracy of the model :  80.78561287269285

confusion Matrix: 
[[1388  197]
 [ 209  319]]

F1_score of the model :  61.11111111111111

voting model:  

list of accuracy:  [80.9929078  80.56737589 79.43262411 82.10227273 79.82954545 77.27272727
 80.96590909 78.97727273 79.26136364 80.39772727]

Accuracy: of the voting classifier using logistic regression,naive bayes and K-NN:  79.97997259832366


In [49]:
##voting with logistic, Naive bayes, KNN and Decision tree!

estimators= []
model1= LogisticRegression()
estimators.append(('logistic',model1))
model2= GaussianNB()
estimators.append(('naive',model2))
model3= KNeighborsClassifier(n_neighbors=83,metric='euclidean')
estimators.append(('KNN',model3))
model4=DecisionTreeClassifier()
estimators.append(('cart',model4))
ensemble=VotingClassifier(estimators)
ensemble.fit(x_train,y_train)
y_ped=ensemble.predict(x_test)
print("Accuracy of the model : ",accuracy_score(y_test,y_ped)*100)
print()
print("confusion Matrix: ")
print(confusion_matrix(y_test,y_ped))
print()
print("F1_score of the model : ", f1_score(y_test,y_ped)*100)
print()
results=model_selection.cross_val_score(model,x,y,cv=kfold)*100
print("voting model:  ")
print()
print("list of accuracy: ",results)
print()
print("Accuracy: of the voting classifier using logistic regression,naive bayes ,K-NN and decision tree : ", results.mean())

C:\Users\Slok\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


Accuracy of the model :  81.21154756270705

confusion Matrix: 
[[1416  169]
 [ 228  300]]

F1_score of the model :  60.18054162487463

voting model:  

list of accuracy:  [80.9929078  80.56737589 79.43262411 82.10227273 79.82954545 77.27272727
 80.96590909 78.97727273 79.26136364 80.39772727]

Accuracy: of the voting classifier using logistic regression,naive bayes ,K-NN and decision tree :  79.97997259832366


In [47]:
#bagging classifier using logistic Regression!
cart=LogisticRegression()
num_tree =100
model = BaggingClassifier(base_estimator=cart, n_estimators= num_tree, random_state=7)

model.fit(x_train,y_train)
y_ped=model.predict(x_test)

print("Accuracy of the model : ",accuracy_score(y_test,y_ped)*100)
print()
print("confusion Matrix: ")
print(confusion_matrix(y_test,y_ped))
print()
print("F1_score of the model : ", f1_score(y_test,y_ped)*100)
print()
results=model_selection.cross_val_score(model,x,y,cv=kfold)*100
print()
print("Ensemble learner model of type bagging: ")
print()
print("list of accuracy: ",results)
print()
print("Accuracy: of bagging classifier using logistic regression model: ", results.mean())
print()

C:\Users\Slok\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\Slok\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\Slok\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\Slok\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\Slok\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this w

C:\Users\Slok\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\Slok\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\Slok\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\Slok\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\Slok\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this w

C:\Users\Slok\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\Slok\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\Slok\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\Slok\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\Slok\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this w

Accuracy of the model :  81.21154756270705

confusion Matrix: 
[[1423  162]
 [ 235  293]]

F1_score of the model :  59.61342828077314



C:\Users\Slok\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\Slok\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\Slok\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\Slok\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\Slok\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this w

C:\Users\Slok\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\Slok\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\Slok\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\Slok\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\Slok\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this w

C:\Users\Slok\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\Slok\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\Slok\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\Slok\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\Slok\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this w

C:\Users\Slok\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\Slok\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\Slok\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\Slok\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\Slok\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this w

C:\Users\Slok\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\Slok\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\Slok\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\Slok\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\Slok\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this w

C:\Users\Slok\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\Slok\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\Slok\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\Slok\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\Slok\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this w

C:\Users\Slok\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\Slok\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\Slok\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\Slok\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\Slok\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this w

C:\Users\Slok\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\Slok\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\Slok\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\Slok\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\Slok\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this w

C:\Users\Slok\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\Slok\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\Slok\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\Slok\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\Slok\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this w

C:\Users\Slok\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\Slok\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\Slok\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\Slok\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\Slok\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this w

C:\Users\Slok\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\Slok\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\Slok\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\Slok\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\Slok\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this w

C:\Users\Slok\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\Slok\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\Slok\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\Slok\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\Slok\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this w

C:\Users\Slok\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\Slok\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\Slok\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\Slok\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\Slok\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this w

C:\Users\Slok\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\Slok\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\Slok\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\Slok\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\Slok\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this w

C:\Users\Slok\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\Slok\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\Slok\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\Slok\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\Slok\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this w

C:\Users\Slok\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\Slok\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\Slok\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\Slok\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\Slok\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this w

C:\Users\Slok\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\Slok\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\Slok\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\Slok\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\Slok\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this w

C:\Users\Slok\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\Slok\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\Slok\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\Slok\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\Slok\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this w

C:\Users\Slok\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\Slok\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\Slok\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\Slok\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\Slok\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this w

C:\Users\Slok\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\Slok\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\Slok\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\Slok\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\Slok\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this w

C:\Users\Slok\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\Slok\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\Slok\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\Slok\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\Slok\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this w

C:\Users\Slok\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\Slok\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\Slok\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\Slok\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\Slok\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this w


Ensemble learner model of type bagging: 

list of accuracy:  [80.9929078  80.         79.71631206 81.96022727 80.53977273 79.11931818
 81.53409091 79.26136364 79.26136364 81.25      ]

Accuracy: of bagging classifier using logistic regression model:  80.36353562217924



C:\Users\Slok\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\Slok\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


In [48]:
#bagging classifier using K-NN!
cart=KNeighborsClassifier(n_neighbors=83,metric='euclidean')
num_tree =100
model = BaggingClassifier(base_estimator=cart, n_estimators= num_tree, random_state=7)

model.fit(x_train,y_train)
y_ped=model.predict(x_test)

print("Accuracy of the model : ",accuracy_score(y_test,y_ped)*100)
print()
print("confusion Matrix: ")
print(confusion_matrix(y_test,y_ped))
print()
print("F1_score of the model : ", f1_score(y_test,y_ped)*100)
print()
results=model_selection.cross_val_score(model,x,y,cv=kfold)*100
print()
print("Ensemble learner model of type bagging: ")
print()
print("list of accuracy: ",results)
print()
print("Accuracy: of bagging classifier using K-NN model: ", results.mean())
print()

Accuracy of the model :  80.8329389493611

confusion Matrix: 
[[1407  178]
 [ 227  301]]

F1_score of the model :  59.781529294935446


Ensemble learner model of type bagging: 

list of accuracy:  [80.9929078  80.56737589 79.43262411 82.10227273 79.82954545 77.27272727
 80.96590909 78.97727273 79.26136364 80.39772727]

Accuracy: of bagging classifier using K-NN model:  79.97997259832366

